### ISSUE TITLE
How to use!

### ISSUE THREAD

**Issue by NERDTimmie** [aresrpg/minecraft-dissector#1]
Hi im wondering how i can use this?

**Comment by DeltaEvo** [comment]
If you are on linux a simple `make install` should do the work
If you are on windows, I don't really know how to install this

I will try to write a readme to try to explain this with more details this week :)

**Comment by NERDTimmie** [comment]
Mabey it works with WLS

**Comment by DeltaEvo** [comment]
I figured out how to compile on windows and I setuped an automatic buld, I will write a readme soon

You can try it with wireshark 3.4 by downloading packet-minecraft.dll here https://github.com/aresrpg/minecraft-dissector/releases/tag/v1.0.0 and put it inside %APPDATA%\Wireshark\plugins\3.4\epan

**Comment by DeltaEvo** [comment]
71fa60732b945302275419ad1a63f51e3ad545aa
